/**
 * TL Manager
 * Copyright (C) 2015 European Commission, provided under the CEF programme
 *
 * This file is part of the "TL Manager" project.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */
package eu.europa.ec.markt.tlmanager.view.pages;

import javax.swing.*;

import eu.europa.ec.markt.tlmanager.core.Configuration;
import eu.europa.ec.markt.tlmanager.core.QNames;
import eu.europa.ec.markt.tlmanager.model.treeNodes.TSLDataNode;
import eu.europa.ec.markt.tlmanager.view.binding.BindingManager;
import eu.europa.ec.markt.tlmanager.view.binding.ElectronicAddressConverter;
import eu.europa.ec.markt.tlmanager.view.binding.InternationalNamesConverter;
import eu.europa.ec.markt.tlmanager.view.binding.NonEmptyMultiLangURIListConverter;
import eu.europa.ec.markt.tlmanager.view.binding.PostalAddressListConverter;
import eu.europa.ec.markt.tlmanager.view.binding.TSPInformationExtensionConverter;
import eu.europa.ec.markt.tlmanager.view.common.TitledPanel;
import eu.europa.ec.markt.tlmanager.view.multivalue.MultiMode;
import eu.europa.ec.markt.tlmanager.view.multivalue.MultivalueButton;
import eu.europa.ec.markt.tsl.jaxb.tsl.TSPInformationType;
import eu.europa.ec.markt.tsl.jaxb.tsl.TSPType;

/**
 * Content page for managing all below a <tsl:TSPInformation/>.
 *
 *
 */

public class TSPInformationPage extends TreeDataPublisher {

    private static final org.slf4j.Logger LOG = org.slf4j.LoggerFactory.getLogger(TSPInformationPage.class);

    /**
     * Instantiates a new tSP information page.
     */
    public TSPInformationPage(JTree jtree) {
        super(jtree);
        initComponents();
        tspTitle.setTitle(uiKeys.getString("TSPInformationPage.tspTitle.title"));
        initBinding();

        additionalSetup();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void setName() {
        setName(TreeDataPublisher.TSP_INFORMATION_PAGE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected void setupMandatoryLabels() {
        setMandatoryLabel(tspNameLabel);
        setMandatoryLabel(postalAddressLabel);
        setMandatoryLabel(electronicAddressLabel);
        setMandatoryLabel(informationURILabel);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tspTitle = new TitledPanel();
        tspNameLabel = new JLabel();
        tspName = new MultivalueButton(MultiMode.MULTILANG_TEXT, Configuration.LanguageCodes.getEnglishLanguage(), null);
        tradeName = new MultivalueButton(MultiMode.MULTILANG_TEXT, Configuration.LanguageCodes.getEnglishLanguage(), null);
        postalAddress = new MultivalueButton(MultiMode.MULTILANG_POSTAL, Configuration.LanguageCodes.getEnglishLanguage(), null);
        electronicAddress = new MultivalueButton(MultiMode.MULTI_MULTILANGANYURI, null, null);
        informationURI = new MultivalueButton(MultiMode.MULTILANG_TEXT, Configuration.LanguageCodes.getEnglishLanguage(), null);
        informationExtension = new MultivalueButton(MultiMode.MULTI_TSPINEX, null, null);
        tspTradeNameLabel = new JLabel();
        postalAddressLabel = new JLabel();
        electronicAddressLabel = new JLabel();
        informationURILabel = new JLabel();
        informationExtensionLabel = new JLabel();

        tspNameLabel.setLabelFor(tspName);
        tspNameLabel.setText(uiKeys.getString("TSPInformationPage.tspNameLabel.text")); // NOI18N

        tspTradeNameLabel.setLabelFor(tradeName);
        tspTradeNameLabel.setText(uiKeys.getString("TSPInformationPage.tspTradeNameLabel.text")); // NOI18N

        postalAddressLabel.setLabelFor(postalAddress);
        postalAddressLabel.setText(uiKeys.getString("TSPInformationPage.postalAddressLabel.text")); // NOI18N

        electronicAddressLabel.setLabelFor(electronicAddress);
        electronicAddressLabel.setText(uiKeys.getString("TSPInformationPage.electronicAddressLabel.text")); // NOI18N

        informationURILabel.setLabelFor(informationURI);
        informationURILabel.setText(uiKeys.getString("TSPInformationPage.informationURILabel.text")); // NOI18N

        informationExtensionLabel.setLabelFor(informationExtension);
        informationExtensionLabel.setText(uiKeys.getString("TSPInformationPage.informationExtensionLabel.text")); // NOI18N

        GroupLayout tspTitleLayout = new GroupLayout(tspTitle);
        tspTitle.setLayout(tspTitleLayout);
        tspTitleLayout.setHorizontalGroup(tspTitleLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(tspTitleLayout.createSequentialGroup().addContainerGap()
              .addGroup(tspTitleLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(informationExtensionLabel).addComponent(postalAddressLabel)
                    .addComponent(tspTradeNameLabel).addComponent(tspNameLabel).addComponent(electronicAddressLabel).addComponent(informationURILabel)).addGap(36, 36, 36).addGroup(
                    tspTitleLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                          .addComponent(tradeName, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                          .addComponent(postalAddress, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                          .addComponent(electronicAddress, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                          .addComponent(informationURI, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                          .addComponent(informationExtension, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                          .addComponent(tspName, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)).addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        tspTitleLayout.setVerticalGroup(tspTitleLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(tspTitleLayout.createSequentialGroup().addContainerGap()
              .addGroup(tspTitleLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(tspName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE).addComponent(tspNameLabel)).addGap(18, 18, 18)
              .addGroup(tspTitleLayout.createParallelGroup(GroupLayout.Alignment.TRAILING).addComponent(tspTradeNameLabel)
                    .addComponent(tradeName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)).addGap(18, 18, 18).addGroup(
                    tspTitleLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                          .addComponent(postalAddress, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                          .addComponent(postalAddressLabel, GroupLayout.Alignment.TRAILING)).addGap(18, 18, 18).addGroup(
                    tspTitleLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(electronicAddressLabel, GroupLayout.Alignment.TRAILING)
                          .addComponent(electronicAddress, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
              .addGap(18, 18, 18).addGroup(tspTitleLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(informationURILabel, GroupLayout.Alignment.TRAILING)
                    .addComponent(informationURI, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
              .addGap(18, 18, 18).addGroup(tspTitleLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(informationExtension, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(informationExtensionLabel, GroupLayout.Alignment.TRAILING)).addContainerGap(31, Short.MAX_VALUE)));

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup().addContainerGap().addComponent(tspTitle, GroupLayout.PREFERRED_SIZE, 359, Short.MAX_VALUE).addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(
              layout.createSequentialGroup().addContainerGap().addComponent(tspTitle, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addContainerGap()));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private MultivalueButton electronicAddress;
    private JLabel electronicAddressLabel;
    private MultivalueButton informationExtension;
    private JLabel informationExtensionLabel;
    private MultivalueButton informationURI;
    private JLabel informationURILabel;
    private MultivalueButton postalAddress;
    private JLabel postalAddressLabel;
    private MultivalueButton tradeName;
    private MultivalueButton tspName;
    private JLabel tspNameLabel;
    private TitledPanel tspTitle;
    private JLabel tspTradeNameLabel;
    // End of variables declaration//GEN-END:variables
    /*
     * (non-Javadoc)
     * 
     * @see javax.swing.event.TreeSelectionListener#valueChanged(javax.swing.event.TreeSelectionEvent)
     */

    private void initBinding() {
        if (bindingManager == null) {
            bindingManager = new BindingManager(this);
        }

        bindingManager.createBindingForComponent(tspName.getMultivaluePanel(), "TSPName", QNames._TSPName);
        bindingManager.appendConverter(new InternationalNamesConverter(), QNames._TSPName);

        bindingManager.createBindingForComponent(tradeName.getMultivaluePanel(), "TSPTradeName", QNames._TSPTradeName);
        bindingManager.appendConverter(new InternationalNamesConverter(), QNames._TSPTradeName);

        bindingManager.createBindingForComponent(postalAddress.getMultivaluePanel(), "postalAddresses", QNames._PostalAddress_QNAME.getLocalPart());
        bindingManager.appendConverter(new PostalAddressListConverter(), QNames._PostalAddress_QNAME.getLocalPart());

        bindingManager.createBindingForComponent(electronicAddress.getMultivaluePanel(), "electronicAddress", QNames._ElectronicAddress_QNAME.getLocalPart());
        bindingManager.appendConverter(new ElectronicAddressConverter(), QNames._ElectronicAddress_QNAME.getLocalPart());

        bindingManager.createBindingForComponent(informationURI.getMultivaluePanel(), "TSPInformationURI", QNames._TSPInformation_QNAME.getLocalPart());
        bindingManager.appendConverter(new NonEmptyMultiLangURIListConverter(), QNames._TSPInformation_QNAME.getLocalPart());

        bindingManager.createBindingForComponent(informationExtension.getMultivaluePanel(), "TSPInformationExtensions", QNames._Extension_QNAME.getLocalPart());
        bindingManager.appendConverter(new TSPInformationExtensionConverter(), QNames._Extension_QNAME.getLocalPart());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void updateViewFromData(TSLDataNode dataNode) {
        this.dataNode = dataNode;
        TSPType tsp = (TSPType) dataNode.getUserObject();
        TSPInformationType tspInformation = tsp.getTSPInformation();
        LOG.debug( "Value changed {}", tsp);

        bindingManager.unbindAll();

        bindingManager.amendSourceForBinding(tspInformation, QNames._TSPName);
        bindingManager.amendSourceForBinding(tspInformation, QNames._TSPTradeName);

        bindingManager.amendSourceForBinding(tspInformation.getTSPAddress(), QNames._PostalAddress_QNAME.getLocalPart());
        bindingManager.amendSourceForBinding(tspInformation.getTSPAddress(), QNames._ElectronicAddress_QNAME.getLocalPart());

        bindingManager.amendSourceForBinding(tspInformation, QNames._TSPInformation_QNAME.getLocalPart());

        bindingManager.amendSourceForBinding(tspInformation, QNames._Extension_QNAME.getLocalPart());

        bindingManager.bindAll();

        // update all the preview information on the multivalue buttons
        electronicAddress.refreshContentInformation();
        informationExtension.refreshContentInformation();
        informationURI.refreshContentInformation();
        postalAddress.refreshContentInformation();
        tradeName.refreshContentInformation();
        tradeName.refreshContentInformation();
        tspName.refreshContentInformation();
    }
}