/*
 * DSS - Digital Signature Services
 *
 * Copyright (C) 2013 European Commission, Directorate-General Internal Market and Services (DG MARKT), B-1049 Bruxelles/Brussel
 *
 * Developed by: 2013 ARHS Developments S.A. (rue Nicolas Bové 2B, L-1253 Luxembourg) http://www.arhs-developments.com
 *
 * This file is part of the "DSS - Digital Signature Services" project.
 *
 * "DSS - Digital Signature Services" is free software: you can redistribute it and/or modify it under the terms of
 * the GNU Lesser General Public License as published by the Free Software Foundation, either version 2.1 of the
 * License, or (at your option) any later version.
 *
 * DSS is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along with
 * "DSS - Digital Signature Services".  If not, see <http://www.gnu.org/licenses/>.
 */

package eu.europa.ec.markt.tlmanager.core;

import javax.xml.namespace.QName;

/**
 * Collection of all <code>QName</code> of objects, that can be generated by the object factories of jaxb.
 *
 * @version $Revision$ - $Date$
 */

public interface QNames {

    // namespaces
    public final static String TSL_NAMESPACE = "http://uri.etsi.org/02231/v2#";

    // Additional Names
    public final static String _TSPName = new String("TSPName");
    public final static String _TSPTradeName = new String("TSPTradeName");
    public final static String _TSLLocation = new String("TSLLocation");
    public final static String _SchemeServiceDefinitionURI = new String("SchemeServiceDefinitionURI");
    public final static String _TSPServiceDefinitionURI = new String("TSPServiceDefinitionURI");
    public final static String _ServiceName = new String("ServiceName");
    public final static String _StatusStartingTime = new String("StatusStartingTime");
    public final static String _TSLSequenceNumber = new String("TSLSequenceNumber");
    public final static String _HistoricalInformationPeriod = new String("HistoricalInformationPeriod");
    public final static String _ListIssueDateTime = new String("ListIssueDateTime");
    public final static String _TSLIdentifier = new String("TSLIdentifier");
    public final static String _TSPInformationURI = new String("TSPInformationURI");

    public final static String _TakenOverByCritical = new String("TakenOverByCritical");
    public final static String _TakenOverByUri = new String("TakenOverByUri");
    public final static String _TakenOverByTSPName = new String("TakenOverByTSPName");
    public final static String _TakenOverBySchemeOperatorName = new String("TakenOverBySchemeOperatorName");
    public final static String _TakenOverBySchemeTerritory = new String("TakenOverBySchemeTerritory");

    public final static String _ExpiredCertsRevocationInfoCritical = new String("ExpiredCertsRevocationInfoCritical");
    public final static String _ExpiredCertsRevocationInfoDate = new String("ExpiredCertsRevocationInfoDate");

    public final static String _QualificationsCritical = new String("QualificationsCritical");
    public final static String _QualificationsQualifiers = new String("QualificationsQualifiers");
    public final static String _QualificationsAssert = new String("QualificationsAssert");

    public final static String _QualificationsKeyUsage = new String("QualificationsKeyUsage");

    public final static String _QualificationsPoliciesList = new String("QualificationsPoliciesList");

    public final static String _CriteriaList = new String("CriteriaList");
    public final static String _KeyUsage = new String("KeyUsage");
    public final static String _KeyUsageBit = new String("KeyUsageBit");

    public final static String _Identifier = new String("Identifier");
    public final static String _URI = new String("URI");
    public final static String _SchemeOperatorAddress = new String("SchemeOperatorAddress");

    // Postal Address
    public final static String _StreetAddress = new String("StreetAddress");
    public final static String _Locality = new String("Locality");
    public final static String _CountryName = new String("CountryName");

    public final static String _OtherInformation = new String("OtherInformation");

    // TSL
    public final static QName _PostalAddresses_QNAME = new QName(TSL_NAMESPACE, "PostalAddresses");
    public final static QName _PointersToOtherTSL_QNAME = new QName(TSL_NAMESPACE, "PointersToOtherTSL");
    public final static QName _SchemeInformationURI_QNAME = new QName(TSL_NAMESPACE, "SchemeInformationURI");
    public final static QName _ServiceTypeIdentifier_QNAME = new QName(TSL_NAMESPACE, "ServiceTypeIdentifier");
    public final static QName _SchemeInformation_QNAME = new QName(TSL_NAMESPACE, "SchemeInformation");
    public final static QName _TrustServiceStatusList_QNAME = new QName(TSL_NAMESPACE, "TrustServiceStatusList");
    public final static QName _ServiceHistory_QNAME = new QName(TSL_NAMESPACE, "ServiceHistory");
    public final static QName _ServiceStatus_QNAME = new QName(TSL_NAMESPACE, "ServiceStatus");
    public final static QName _TSPService_QNAME = new QName(TSL_NAMESPACE, "TSPService");
    public final static QName _OtherTSLPointer_QNAME = new QName(TSL_NAMESPACE, "OtherTSLPointer");
    public final static QName _ElectronicAddress_QNAME = new QName(TSL_NAMESPACE, "ElectronicAddress");
    public final static QName _ServiceDigitalIdentity_QNAME = new QName(TSL_NAMESPACE, "ServiceDigitalIdentity");
    public final static QName _TSPServices_QNAME = new QName(TSL_NAMESPACE, "TSPServices");
    public final static QName _Extension_QNAME = new QName(TSL_NAMESPACE, "Extension");
    public final static QName _PostalAddress_QNAME = new QName(TSL_NAMESPACE, "PostalAddress");
    public final static QName _PolicyOrLegalNotice_QNAME = new QName(TSL_NAMESPACE, "PolicyOrLegalNotice");
    public final static QName _SchemeTypeCommunityRules_QNAME = new QName(TSL_NAMESPACE, "SchemeTypeCommunityRules");
    public final static QName _SchemeOperatorName_QNAME = new QName(TSL_NAMESPACE, "SchemeOperatorName");
    public final static QName _AdditionalServiceInformation_QNAME = new QName(TSL_NAMESPACE, "AdditionalServiceInformation");
    public final static QName _ServiceSupplyPoints_QNAME = new QName(TSL_NAMESPACE, "ServiceSupplyPoints");
    public final static QName _NextUpdate_QNAME = new QName(TSL_NAMESPACE, "NextUpdate");
    public final static QName _SchemeTerritory_QNAME = new QName(TSL_NAMESPACE, "SchemeTerritory");
    public final static QName _DistributionPoints_QNAME = new QName(TSL_NAMESPACE, "DistributionPoints");
    public final static QName _TSLType_QNAME = new QName(TSL_NAMESPACE, "TSLType");
    public final static QName _TrustServiceProvider_QNAME = new QName(TSL_NAMESPACE, "TrustServiceProvider");
    public final static QName _ServiceInformation_QNAME = new QName(TSL_NAMESPACE, "ServiceInformation");
    public final static QName _ServiceDigitalIdentities_QNAME = new QName(TSL_NAMESPACE, "ServiceDigitalIdentities");
    public final static QName _ServiceHistoryInstance_QNAME = new QName(TSL_NAMESPACE, "ServiceHistoryInstance");
    public final static QName _TrustServiceProviderList_QNAME = new QName(TSL_NAMESPACE, "TrustServiceProviderList");
    public final static QName _ExpiredCertsRevocationInfo_QNAME = new QName(TSL_NAMESPACE, "ExpiredCertsRevocationInfo");
    public final static QName _AdditionalInformation_QNAME = new QName(TSL_NAMESPACE, "AdditionalInformation");
    public final static QName _TSPInformation_QNAME = new QName(TSL_NAMESPACE, "TSPInformation");
    public final static QName _SchemeName_QNAME = new QName(TSL_NAMESPACE, "SchemeName");
    public final static QName _StatusDeterminationApproach_QNAME = new QName(TSL_NAMESPACE, "StatusDeterminationApproach");
    public final static QName _SchemeExtensions_QNAME = new QName(TSL_NAMESPACE, "SchemeExtensions");

    // TSLX
    public final static QName _MimeType_QNAME = new QName("http://uri.etsi.org/02231/v2/additionaltypes#", "MimeType");
    public final static QName _ExtendedKeyUsage_QNAME = new QName("http://uri.etsi.org/02231/v2/additionaltypes#", "ExtendedKeyUsage");
    public final static QName _CertSubjectDNAttribute_QNAME = new QName("http://uri.etsi.org/02231/v2/additionaltypes#", "CertSubjectDNAttribute");
    public final static QName _X509CertificateLocation_QNAME = new QName("http://uri.etsi.org/02231/v2/additionaltypes#", "X509CertificateLocation");
    public final static QName _PublicKeyLocation_QNAME = new QName("http://uri.etsi.org/02231/v2/additionaltypes#", "PublicKeyLocation");
    public final static QName _TakenOverBy_QNAME = new QName("http://uri.etsi.org/02231/v2/additionaltypes#", "TakenOverBy");

    // ECC
    public final static QName _Qualifications_QNAME = new QName("http://uri.etsi.org/TrstSvc/SvcInfoExt/eSigDir-1999-93-EC-TrustedList/#", "Qualifications");

    // XADES
    public final static QName _UnsignedDataObjectProperties_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "UnsignedDataObjectProperties");
    public final static QName _SignatureTimeStamp_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SignatureTimeStamp");
    public final static QName _ArchiveTimeStamp_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "ArchiveTimeStamp");
    public final static QName _AttrAuthoritiesCertValues_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "AttrAuthoritiesCertValues");
    public final static QName _CompleteRevocationRefs_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "CompleteRevocationRefs");
    public final static QName _CounterSignature_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "CounterSignature");
    public final static QName _QualifyingProperties_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "QualifyingProperties");
    public final static QName _SigningCertificate_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SigningCertificate");
    public final static QName _XAdESTimeStamp_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "XAdESTimeStamp");
    public final static QName _AllDataObjectsTimeStamp_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "AllDataObjectsTimeStamp");
    public final static QName _SignerRole_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SignerRole");
    public final static QName _RevocationValues_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "RevocationValues");
    public final static QName _SignaturePolicyIdentifier_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SignaturePolicyIdentifier");
    public final static QName _Any_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "Any");
    public final static QName _Include_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "Include");
    public final static QName _SigAndRefsTimeStamp_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SigAndRefsTimeStamp");
    public final static QName _DataObjectFormat_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "DataObjectFormat");
    public final static QName _SignedProperties_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SignedProperties");
    public final static QName _AttributeRevocationRefs_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "AttributeRevocationRefs");
    public final static QName _IndividualDataObjectsTimeStamp_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "IndividualDataObjectsTimeStamp");
    public final static QName _SPUserNotice_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SPUserNotice");
    public final static QName _UnsignedProperties_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "UnsignedProperties");
    public final static QName _SignedSignatureProperties_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SignedSignatureProperties");
    public final static QName _AttributeRevocationValues_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "AttributeRevocationValues");
    public final static QName _ObjectIdentifier_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "ObjectIdentifier");
    public final static QName _OtherTimeStamp_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "OtherTimeStamp");
    public final static QName _RefsOnlyTimeStamp_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "RefsOnlyTimeStamp");
    public final static QName _SPURI_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SPURI");
    public final static QName _SignedDataObjectProperties_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SignedDataObjectProperties");
    public final static QName _ReferenceInfo_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "ReferenceInfo");
    public final static QName _SignatureProductionPlace_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SignatureProductionPlace");
    public final static QName _EncapsulatedPKIData_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "EncapsulatedPKIData");
    public final static QName _CommitmentTypeIndication_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "CommitmentTypeIndication");
    public final static QName _UnsignedSignatureProperties_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "UnsignedSignatureProperties");
    public final static QName _QualifyingPropertiesReference_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "QualifyingPropertiesReference");
    public final static QName _CertificateValues_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "CertificateValues");
    public final static QName _SigningTime_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SigningTime");
    public final static QName _AttributeCertificateRefs_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "AttributeCertificateRefs");
    public final static QName _CompleteCertificateRefs_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "CompleteCertificateRefs");

    // XMLDSIG
    public final static QName _PGPData_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "PGPData");
    public final static QName _SPKIData_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "SPKIData");
    public final static QName _CanonicalizationMethod_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "CanonicalizationMethod");
    public final static QName _Manifest_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "Manifest");
    public final static QName _Transforms_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "Transforms");
    public final static QName _SignatureMethod_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "SignatureMethod");
    public final static QName _KeyInfo_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "KeyInfo");
    public final static QName _DigestMethod_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "DigestMethod");
    public final static QName _MgmtData_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "MgmtData");
    public final static QName _SignedInfo_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "SignedInfo");
    public final static QName _Object_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "Object");
    public final static QName _X509Data_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "X509Data");
    public final static QName _SignatureProperties_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "SignatureProperties");
    public final static QName _KeyName_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "KeyName");
    public final static QName _RetrievalMethod_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "RetrievalMethod");
    public final static QName _SignatureProperty_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "SignatureProperty");
    public final static QName _Reference_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "Reference");
    public final static QName _RSAKeyValue_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "RSAKeyValue");
    public final static QName _Signature_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "Signature");
    public final static QName _DSAKeyValue_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "DSAKeyValue");
    public final static QName _SignatureValue_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "SignatureValue");
    public final static QName _Transform_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "Transform");
    public final static QName _DigestValue_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "DigestValue");
    public final static QName _KeyValue_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "KeyValue");
    public final static QName _SignatureMethodTypeHMACOutputLength_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "HMACOutputLength");
    public final static QName _SPKIDataTypeSPKISexp_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "SPKISexp");
    public final static QName _TransformTypeXPath_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "XPath");
    public final static QName _PGPDataTypePGPKeyID_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "PGPKeyID");
    public final static QName _PGPDataTypePGPKeyPacket_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "PGPKeyPacket");
    public final static QName _X509DataTypeX509IssuerSerial_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "X509IssuerSerial");
    public final static QName _X509DataTypeX509Certificate_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "X509Certificate");
    public final static QName _X509DataTypeX509SKI_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "X509SKI");
    public final static QName _X509DataTypeX509SubjectName_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "X509SubjectName");
    public final static QName _X509DataTypeX509CRL_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "X509CRL");
}